# .github/workflows/chromatic.yml

name: "Chromatic"

# https://www.chromatic.com/docs/github-actions/#recommended-configuration-for-build-events
on: push

jobs:
  chromatic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        env:
          NPM_TOKEN: ${{ secrets.JFROG_ACCESS_TOKEN }}
        run: |
          echo -e "\n//dpbuild.jfrog.io/:_authToken=${NPM_TOKEN}" >> .npmrc
          npm ci

      - name: Publish to Chromatic
        uses: chromaui/action@latest
        with:
          # âš ï¸ Make sure to configure a `CHROMATIC_PROJECT_TOKEN` repository secret
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          autoAcceptChanges: "main" # ğŸ‘ˆ Option to accept all changes on main
          exitOnceUploaded: true
          skip: "@(renovate/**|dependabot/**)" # ğŸ‘ˆ Option to skip Chromatic for certain branches
          zip: true
